### ISSUE TITLE
'type' object is not subscriptable

### ISSUE THREAD

**Issue by SaraDadjouy** [tsbinns/mni_to_region#1]
Hi. I'm trying to import atlas_browser but when I run the command "from atlas_browser import AtlasBrowser", I get this error: 'type' object is not subscriptable
Why is that and how can I fix it?

**Comment by tsbinns** [comment]
Hi, I did not encounter this issue before, so I am not sure why this is occurring.

I have just updated the repository to v1.0.0 and uploaded it as a package which you can install using pip ("pip install mni-to-atlas"): https://pypi.org/project/mni-to-atlas/
Here there are updated instructions on installing and using the tool. I hope installing the tool in this way will correct any such issues.

Let me know if you have any further questions!

**Comment by Atom97** [comment]
Hello!

When I'm trying to import the library, I get a syntax error on line 336 of the init file:

region_id = int(self._atlas[*atlas_coords])
                                             ^
SyntaxError: invalid syntax
