### ISSUE TITLE
Syntax error while importing

### ISSUE THREAD

**Issue by caggursoy** [tsbinns/mni_to_region#3]
Hi,

I am receiving the following runtime error whenever I try to import the package. Here's how I try to import it

`from mni_to_atlas import AtlasBrowser`

```
Traceback (most recent call last):

  File ~/.conda/envs/nipype/lib/python3.10/site-packages/IPython/core/interactiveshell.py:3526 in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  Cell In[11], line 11
    from mni_to_atlas import AtlasBrowser

  File ~/.conda/envs/nipype/lib/python3.10/site-packages/mni_to_atlas/__init__.py:3
    from .atlas_browser import AtlasBrowser

  File ~/.conda/envs/nipype/lib/python3.10/site-packages/mni_to_atlas/atlas_browser.py:336
    region_id = int(self._atlas[*atlas_coords])
                    ^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
```

And here's my system information:
- Ubuntu 22.04
- Python 3.9.13
- conda 22.9.0
- Running on JupyterLab, so:
  - IPython          : 7.31.1
  - ipykernel        : 6.15.2
  - ipywidgets       : 7.6.5
  - jupyter_client   : 7.3.4
  - jupyter_core     : 4.11.1
  - jupyter_server   : 1.18.1
  - jupyterlab       : 3.4.4
  - nbclient         : 0.5.13
  - nbconvert        : 6.4.4
  - nbformat         : 5.5.0
  - notebook         : 6.4.12
  - qtconsole        : 5.3.2
  - traitlets        : 5.1.1

I would be glad if you can offer any help with this regard

**Comment by caggursoy** [comment]
### Update
If I remove the * character from _line 336_ of _atlas_browser.py_ I encounter a completely different error. 
Original script
`region_id = int(self._atlas[*atlas_coords])`
Edited script
`region_id = int(self._atlas[atlas_coords])`

Please see the error below, when the edited script is run with the following parameters:
`coord = np.array([0,40,-4])`
`atlas.find_regions(coord)`
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/zi/home/cagatay.guersoy/.conda/envs/nipype/lib/python3.10/site-packages/mni_to_atlas/atlas_browser.py", line 141, in find_regions
    region = self._find_region(atlas_coords)
  File "/zi/home/cagatay.guersoy/.conda/envs/nipype/lib/python3.10/site-packages/mni_to_atlas/atlas_browser.py", line 336, in _find_region
    region_id = int(self._atlas[atlas_coords])
TypeError: only length-1 arrays can be converted to Python scalars
```

**Comment by tsbinns** [comment]
Thanks for bringing this to my attention! I haven't touched this code in a while so I'll have to investigate what's going wrong, will try to have a solution in the coming days.

Cheers!

**Comment by tsbinns** [comment]
@caggursoy Please can you try updating your Python version to >= 3.11, that should stop this from happening.

Will try to release a new version in the coming days as a more permanent fix.

**Comment by rjalejandro** [comment]
is there a way to fix this issue without updating python? similar error here (just trying to run [the example](https://pypi.org/project/mni-to-atlas/)):
```
Traceback (most recent call last):

  File [/my-env/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3550](http://localhost:8888/lab/tree/my-env/my-env/lib/python3.9/site-packages/IPython/core/interactiveshell.py#line=3549) in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  Cell In[2], line 2
    from mni_to_atlas import AtlasBrowser

  File [/my-env/lib/python3.9/site-packages/mni_to_atlas/__init__.py:3](http://localhost:8888/lab/tree/my-env/my-env/lib/python3.9/site-packages/mni_to_atlas/__init__.py#line=2)
    from .atlas_browser import AtlasBrowser

  File [/my-env/lib/python3.9/site-packages/mni_to_atlas/atlas_browser.py:336](http://localhost:8888/lab/tree/my-env/my-env/lib/python3.9/site-packages/mni_to_atlas/atlas_browser.py#line=335)
    region_id = int(self._atlas[*atlas_coords])
                                             ^
SyntaxError: invalid syntax
```
thanks!

**Comment by tsbinns** [comment]
Hi @rjalejandro, I just created a new release [v1.0.1](https://pypi.org/project/mni-to-atlas/1.0.1/) that should work with Python v3.9. Cheers!

**Comment by rjalejandro** [comment]
It worked beautifully.

Thanks @tsbinns for your fast help!
